name: spray_tool
description: Calculate dosages for spray-bottle medicine applicators.
version: 1.0.0+1
repository: https://github.com/tytydraco/spray_tool
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  basil:
    git: https://github.com/tytydraco/basil
  icons_launcher: ^2.0.5
  very_good_analysis: any

flutter:
  uses-material-design: true

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true
